### ISSUE TITLE
Make EliteAPI implement interfaces

### ISSUE THREAD

**Issue by MisterJack49** [Somfic/EliteAPI#10]
Hi,

I'm working on a little project with your API which is great by the way and I think it would be nice if EliteAPI came packaged with interfaces like IEliteDangerousAPI for dependency injection for example.

**Comment by Somfic** [comment]
Hello,

Could you please elaborate on which services you had in mind?

**Comment by MisterJack49** [comment]
I'm using a .Net Core app and I wanted to do `services.AddSingletion<IEliteDangerousAPI, EliteDangerousAPI>(x=> new EliteDangerousAPI(journalPath))` but without an interface I don't think it's possible.

**Comment by Somfic** [comment]
This has been added in v2.0.1.0. If you have any issues or need changes be sure to let me know / make a pull request! :)

Thanks for using the library as well!
