### ISSUE TITLE
Default or sample ini file is missing

### ISSUE THREAD

**Issue by tbayart** [Somfic/EliteAPI#217]
I downloaded and installed EliteAPI v3.0.0-alpha3785 from https://github.com/EliteAPI/EliteAPI/releases
In the log panel i can see the following
```
EliteAPI could not be started
Journal directory not found : The journal directory does not exist
```
and
`No valid journal directory could not be found, please specify the correct journal directory in the configuration`

I looked into install folder but could not find any configuration file.

**Comment by Somfic** [comment]
Hi.

See [appsettings.json](https://github.com/Somfic/EliteAPI/blob/main/Example/appsettings.json) for an example configuration.
