### ISSUE TITLE
Wrong check in GetSavedGamesDirectory

### ISSUE THREAD

**Issue by tbayart** [Somfic/EliteAPI#218]
In journalDirectoryProvider the return value of SHGetKnownFolderPath if compared with 0 the wrong way.
`if (result > 0) return Marshal.PtrToStringUni(path);`
the test should be 
`if (result == 0)`

<html>
<body>

Name | Description | Value
-- | -- | --
S_OK | Operation successful | 0x00000000

</body>
</html>

Source: [Common HRESULT Values](https://docs.microsoft.com/en-US/windows/win32/seccrypto/common-hresult-values)

**Comment by Somfic** [comment]
Thanks! Fixed in [this commit](https://github.com/EliteAPI/EliteAPI/commit/df8667c3f45a3985709371348362686e339df97b).
