### ISSUE TITLE
Suggestion : Move server to a separate project

### ISSUE THREAD

**Issue by tbayart** [Somfic/EliteAPI#219]
I suggest you keep EliteAPI as-is and create a separate project referencing the EliteAPI nuget package.
This way you avoid pushing UI or server related modifications to the API itself.

**Comment by Somfic** [comment]
Hi,

I agree. Server code has been moved to [EliteAPI/Server](https://github.com/EliteAPI/EliteAPI.Server) and Web API code has been moved to [EliteAPI/Web](https://github.com/EliteAPI/EliteAPI.Web).

Thank you for your suggestion!
