### ISSUE TITLE
Journal monitor will not work in some cases

### ISSUE THREAD

**Issue by DarkWanderer** [Somfic/EliteAPI#24]
Current implementation of detecting Elite's journal folder will not work when:

- User name does not match user folder name
- `Saved games` folder name is localized
- User profile folder is on a different drive

Ref: https://github.com/EliteAPI/EliteAPI/blob/c55d8cb1548c05bf7bd7f7c980c961e515b66669/EliteAPI/EliteDangerousAPI.cs#L33

Correct way to implement this would be using `SHGetKnownFolderPath`
https://github.com/DarkWanderer/Elite-Log-Agent/blob/414cfe9a2c4947a1fd8f5ccfc4e9a09abc8716df/Controller/SavedGamesDirectoryHelper.cs

**Comment by Somfic** [comment]
Thank you for the improvement!  I will implement this shortly.

**Comment by Somfic** [comment]
This has been implemented, again, thanks!
