### ISSUE TITLE
EliteMacro seems to disrupt VoiceMacro installation

### ISSUE THREAD

**Issue by WesCook** [Somfic/EliteAPI#26]
Steps: I installed VoiceMacro 1.3.1, then installed EliteMacro v2.2.14.870.  When running VoiceMacro I now receive this error:

![image](https://user-images.githubusercontent.com/792101/70562480-51f42380-1b41-11ea-9fcf-71c59f9ddf35.png)

Exiting that shows:

![image](https://user-images.githubusercontent.com/792101/70562643-aac3bc00-1b41-11ea-8787-1e3aeaed9987.png)

Having the installer in the same folder seems to resolve the issue.  I ran the repair tool and I can now use the tool as expected.

![image](https://user-images.githubusercontent.com/792101/70562818-ff673700-1b41-11ea-81d7-67ce4b1d3d10.png)

**Comment by Somfic** [comment]
Hi @WesCook, 

EliteMacro checks whether there's a new EliteMacro version available before every startup, perhaps that's what is causing this issue. It checks its own version against [this](https://raw.githubusercontent.com/EliteAPI/EliteAPI/master/EliteAPI/versioncontrol.version) raw file on GitHub which always contains the latest version.

I do not develop VoiceMacro, I only work on the plugin, EliteMacro. If you keep having issues with VoiceMacro, I suggest you contact the developer of VoiceMacro, DRAGNET. He's in the [EliteAPI discord](discord.gg/jwpFUPZ) if you'd like to contact him.

I'm glad you were able to fix this yourself and thank you for bringing this to my attention. I apologise for any inconveniences.

Let me know if you run into any more issues!

**Comment by WesCook** [comment]
Hi Somfic,

I realize you develop the plugin, not the original application.  I reported it here though as VoiceMacro works as expected until EliteMacro is installed.  Apologies if I did not make that clear.

I know there's not a lot of info to go on here, so if the issue can't be reproduced then feel free to mark this as closed.  I thought I'd better report it though in case others were having the same issue.

Thanks.

**Comment by Somfic** [comment]
Hi @WesCook,

Okay, I understand :) I was not able to reproduce the issue at this moment. 

I'll leave it open for now, in case I can reproduce this error in the future. Let me know when you've got more information on this.

Thank you for using EliteAPI!
