### ISSUE TITLE
I get "Could not invoke status event 'HasLatlong'" after EliteAPI.Start()

### ISSUE THREAD

**Issue by fmjensen** [Somfic/EliteAPI#27]
This shows up in the console:
`Error   ┬  Could not invoke status event 'HasLatlong', it might not have been added yet.
        ├  Object reference not set to an instance of an object.
        ╞  at EliteAPI.Status.StatusWatcher.TriggerIfDifferent(GameStatus oldStatus, GameStatus newStatus)`

Logging is configured like `EliteAPI.Logger.UseConsole(Severity.Info)`

Am i doing something wrong?

**Comment by Somfic** [comment]
Thank you for reporting your issue, I'll get on it.

**Comment by fmjensen** [comment]
Het is niet urgent ;-) - Vrolijk kerstfeest - and thank you for the amazing work you have put into this!

**Comment by Somfic** [comment]
Gelukkig nieuw jaar!

Thank you! It's great to know people use EliteAPI for their own projects.
The `HasLatLong` error should no longer occur in [v2.3.0.0](https://github.com/EliteAPI/EliteAPI/releases/tag/v2.3.0.0), but feel free to reopen this comment if it pops up again!
