### ISSUE TITLE
The logging severity level order are confusing to me.

### ISSUE THREAD

**Issue by fmjensen** [Somfic/EliteAPI#29]
EliteAPI.Logger.UseConsole(Severity Level) are ordered like 
```
   Success = 0,
   Error = 1,
   Warning = 2,
   Info = 3,
   Debug = 4,
   Special = 5
```
This hurts my brain ;-) so i ask if there is a chance these levels cound be ordered like:
```
   No Logging = 0
   Success = 1,
   Info = 2,
   Warning = 3,
   Error = 4,
   Debug = 5,
   Special = 6
```
Where 0 would turn logging completely off.
I may be misunderstanding somthing about the logging, but I cant seem to turn logging completely off if it have been enabled...

Happy NewYear!! :-)

**Comment by Somfic** [comment]
Hi fmjensen,

Your timing is spot on, I am rewriting the entire logging system.
Rather than using the enum to turn logging off and on, I propose `Enable()` and `Disable()` methods. Would that serve your purpose?

Happy new year!!

**Comment by fmjensen** [comment]
`Enable() ` and ` Disable()` methods will be great !

**Comment by Somfic** [comment]
You'll now be able to use `EliteAPI.Logger.Disable()` and `Enable()` in [v2.3.0.0](https://github.com/EliteAPI/EliteAPI/releases/tag/v2.3.0.0).

I am using my own logging system, if you'd like to take a look at it, you can do so [here](https://github.com/Somfic/Somfic/tree/master/Somfic/Logging).

Happy 2020 :)
