### ISSUE TITLE
Support for Status.json

### ISSUE THREAD

**Issue by MorGuux** [Somfic/EliteAPI#3]
Hi, I would like support for the status.json file, and maybe the other .json files, in EliteAPI. I'm using this library right now and it works flawlessly, but it's missing some data that would be really nice to have.

Cheers,
Morgan

**Comment by Somfic** [comment]
Thank you for the kind words!

I'll start work on this right away.

**Comment by Somfic** [comment]
The feature has been added.

You can now do `EliteAPI.Status.FireGroup` to get the current FireGroup.
This also works for ModulesInfo, Outfitting, Cargo and Shipyard.

Thank you for using this lib, fly save o7!

**Comment by MorGuux** [comment]
Brilliant, thanks mate, really appreciate your quick support :D

**Comment by Somfic** [comment]
Full support for all flags are now added.

Information for items like `EliteAPI.Status.SilentRunning`, `LandingGear`, `FsdCharging` and more are now available.
