### ISSUE TITLE
missing fields from more recent ED log versions ?

### ISSUE THREAD

**Issue by mhwlng** [Somfic/EliteAPI#35]
see changelog in :

http://hosting.zaonce.net/community/journal/v26/Journal-Manual-v26.pdf

I'm not seeing for example  :

MissionAcceptedInfo:
  DestinationStation
  NewDestinationSystem
  NewDestinationStation
  Wing
  Donation
  Donated
  Target
  TargetType
  TargetFaction
  KillCount

CargoInfo:
CollectCargoInfo:
EjectCargoInfo:
 MissionId

FSDJumpInfo
 Body

3 new status flags:
29 536870912 2000 0000 Altitude from Average radius
30 1073741824 4000 0000 fsdJump
31 2147483648 8000 0000 srvHighBeam 

etc.

**Comment by Somfic** [comment]
Hi mhwlng,

Thank you for letting me know, I'll update the events to the latest Journal version asap

**Comment by tommyatkadx** [comment]
Can you re-open, I'll like to have the KillCount please

**Comment by tommyatkadx** [comment]
no idea how to pull request, but simply add:
[JsonProperty("KillCount")] public int KillCount { get; private set; }

to Event\Models\MissionAcceptedEvent.cs

=-)
