### ISSUE TITLE
Automatic start shows up as automatic docking

### ISSUE THREAD

**Issue by Aaron2550** [Somfic/EliteAPI#41]
When using the automatic start feature it shows up as "having autopilot dock them at xxx"

**Comment by Somfic** [comment]
Hi @Aaron2550, could you include the log file of the session in which this occured?
 

It should be located in your VoiceAttack/VoiceMacro main directory

**Comment by Aaron2550** [comment]
Woah hold on, I think im in the wrong repository. This is an issue with EliteHook, oups
