### ISSUE TITLE
Missing scan-event parameters

### ISSUE THREAD

**Issue by Envisitor** [Somfic/EliteAPI#42]
Parameters of the scan-event for the case that the scanned body is a star are missing.
You find an excerp from the [journal-doc 3.4 documentation by Frontier Developements](http://hosting.zaonce.net/community/journal/v25/Journal-Manual-v25.pdf) attached to this message. 

[ScanEvent_Parameters_Star.txt](https://github.com/EliteAPI/EliteAPI/files/4369293/ScanEvent_Parameters_Star.txt)

Sincerly,
Envisitor

**Comment by Somfic** [comment]
Hi Envisitor, thank you for your issue.

I'm currently updating all events to [v26](http://hosting.zaonce.net/community/journal/v26/Journal-Manual-v26.pdf) of the Journal manual and adding documentation. I'll try to add/update all events asap.

**Comment by Envisitor** [comment]
Thanks for the quick answer Somfic. 
I couldn't find the v26 documentation in Frontier Developements' forum, so thank you very much for the link.

**Comment by Somfic** [comment]
These properties have been added to the Scan event in the dev branch, you can view the event file [here](https://github.com/EliteAPI/EliteAPI/blob/dev/EliteAPI/Event/Models/ScanEvent.cs).
