### ISSUE TITLE
Events passed to AllEvents from JournalParser are JSON objects

### ISSUE THREAD

**Issue by SilkyPants** [Somfic/EliteAPI#44]
I noticed on startup - that the event passed from the `JournalParser.ProcessJson` method is the raw JSON object, as opposed to the event that is parsed `parsedEvent`.

This seems like the event object that is parsed successfully should also be passed along to the AllEvents handler, as the individual event handler is fired with this same object as well.

See: https://github.com/EliteAPI/EliteAPI/pull/43

**Comment by Somfic** [comment]
Well noted, #43 has been merged, thanks!
