### ISSUE TITLE
Some data to share ...

### ISSUE THREAD

**Issue by saturnineNL** [Somfic/EliteAPI#6]
don't know how to contact you, so this is the easiest way.
I am working on some journal programming and want to share the event data i collected
I Filtered each event i have encountered over the last six months, and added them in a google sheet.
(note the timestamps are replaced with ID) each event has 2 rows: first is the fieldnames, second the values.

I hope I can help you a bit with your work.  
https://docs.google.com/spreadsheets/d/1F2iLmPsce8iHYtYTCGQsHkLzVY_VJWhliyRbecCsuqU/edit?usp=sharing

Greetings Saturnine

**Comment by Somfic** [comment]
Hey Saturine,

Thank you for the data, it can certainly be put to great use!
I'll be checking if you have some events in your list that I hadn't encountered before later today.

Again, thank you!!

Fly save o7

**Comment by Somfic** [comment]
These are all the differences I could find:

`AsteroidCracked
ChangeCrewRole
DatalinkScan
DatalinkVoucher
DataScanned
EngineerContribution
FactionKillBond
JetConeBoost
MaterialTrade
MissionFailed
ModuleStore
Passengers
PayBounties
Promotion
RebootRepair
Screenshot
ShieldState
Synthesis`

I will try to recreate and add all these events in-game.
Thank you for the contribution!

o7
