### ISSUE TITLE
Deluge of [WARN]s - good luck

### ISSUE THREAD

**Issue by Kaizen86** [Somfic/EliteAPI#79]
Under normal operation, there are lots of warnings from the API. I have collated all the warnings from my output into two lists, one being vastly smaller than the other. I have tried to keep duplicates to a minimum for brevity, but it is possible I missed some. (There were tons of repetitive Pip warnings)

List including tracebacks: https://pastebin.com/jDUKYSs1

Condensed list: https://pastebin.com/VAJmD7YS

Hope this is useful, or if you already knew about this then perhaps it could be a checklist.

**Comment by Somfic** [comment]
Hi Blattoid!

Which alpha release are you using?

**Comment by Kaizen86** [comment]
3.0.0-alpha2

**Comment by Somfic** [comment]
I had already developed a (potential) fix for this pretty big issue, I just hadn't added it to a prerelease yet.

Alpha 3 should take care of all of these warnings 🤞

**Comment by Kaizen86** [comment]
Yep, it fixed everything!

**Comment by Kaizen86** [comment]
Wait nevermind they still pop up. Sorry for the false positive, they didn't show up immedately.

**Comment by Somfic** [comment]
This seems to be caused by the API not being able to read the contents of the Status.json file, most likely due to the file being written to by the game at the exact moment the API tries to read its contents

**Comment by Somfic** [comment]
I've added a check for this now. It'll skip processing and try to read the contents again in the next API tick in case the file is locked or unreadable, this should fix the issue

Edit: I've done some testing and it seems to work properly now
