### ISSUE TITLE
Event for ship status?

### ISSUE THREAD

**Issue by TechInterMezzo** [Somfic/EliteAPI#9]
Hi, this library seems great so far!

Is there an event for the change of the ship status?
I hope I can detect when my ship is not masslocked anymore.

**Comment by Somfic** [comment]
There currently is not, but I'll add it on my list of things to do!

**Comment by Somfic** [comment]
This feature has been added in release v2.0.0.1.

```csharp
api.Events.StatusGearEvent += ...
```

or in VoiceAttack: 

Command name: `((EliteAPI.Status.Gear))`.

**Comment by TechInterMezzo** [comment]
Thank you!

There is one thing in the code that I saw which concerns me:

It's the StatusWatcher constructor.
The FileSystemWatcher object only exists in the constructor.
Isn't there a risk that the object gets garbage collected some time after it goes out of scope and stops working?

**Comment by Somfic** [comment]
That could actually be an issue, yes. I'll look into it, thank you
